config/routes.rb
Rails.application.routes.draw do

  root :to => 'main#index'

  get '/features' => 'main#features'
  get '/features/:id' => 'main#feature_show'
  get '/calendar' => 'main#calendar'
  get '/trend' =>'main#trend'
  get '/trend/:id' => 'main#trend_show'
  get '/oncourt' => 'main#oncourt'
  get '/oncourt/:id' => 'main#oncourt_show'
  get '/streetsnap' => 'main#streetsnap'
  get '/streetsnap/:id' => 'main#streetsnap_show'
  get '/rumors' => 'main#rumors'
  get '/rumors/:id' => 'main#rumor_show'
  get '/privacy' => 'main#privacy'
  get '/contact_us' => 'main#contact'
  get '/search' => 'main#search'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :main do
  	collection do
  		get 'get_posts'
      post 'change_language'
      post 'send_contact_us'
      post 'post_rating'
      post 'subscribe'
  	end
  end

  get '/admin', :to => 'admin/dashboard#index', :as => :admin_root

  devise_for :admin_users, :controllers => {:sessions => 'admin/sessions', :registrations => "admin/registrations"}, :skip => [:sessions, :registrations]
  devise_scope :admin_user do
    get 'admin/login' => 'admin/sessions#new', :as => :new_admin_user_session
    post 'admin/login' => 'admin/sessions#create', :as => :admin_user_session
    delete 'admin/logout' => 'admin/sessions#destroy', :as => :destroy_admin_user_session
    get 'admin/register' => 'admin/registrations#new', :as => :new_admin_user_registration
    post 'admin/register' => 'admin/registrations#create', :as => :admin_user_registration
    get 'admin/register/:id/edit' => 'admin/registrations#edit', :as => :edit_admin_user_registration
    put 'admin/register' => 'admin/registrations#update'
  end

  namespace :admin do
  	resources :posts do
      collection do
        get 'get_posts'
        post 'send_newsletter'
      end
      member do
        delete 'delete_subscriber'
      end
    end
    resources :feature_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :calendar_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :trend_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :on_court_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :rumor_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :street_snap_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :admin_users
  end

  get '/sitemap.xml', :to => 'sitemap#index', :defaults => {:format => 'xml'}

  namespace :api do
    scope :v0 do
      scope :home_posts do
        get '/' => 'home_posts#index'
      end
      scope :featured_posts do
        get '/' => 'featured_posts#index'
        get '/:id' => 'featured_posts#show'
      end
      scope :oncourt_posts do
        get '/' => 'oncourt_posts#index'
        get '/:id' => 'oncourt_posts#show'
      end
      scope :trend_posts do
        get '/' => 'trend_posts#index'
        get '/:id' => 'trend_posts#show'
      end
      scope :streetsnap_posts do
        get '/' => 'streetsnap_posts#index'
        get '/:id' => 'streetsnap_posts#show'
      end
      scope :rumor_posts do
        get '/' => 'rumor_posts#index'
        get '/:id' => 'rumor_posts#show'
      end
      scope :calendar_posts do
        get '/' => 'calendar_posts#index'
      end
      get '/search' => 'api_base#search'
      post '/rate' => 'api_base#rate'
      post '/email' => 'api_base#email'
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord

	enum :post_type => [:POST, :NEWS]
	enum :pointer_type => [:FEATURES, :ON_COURT, :TREND, :CALENDAR, :STREET_SNAP, :RUMORS]

	scope :latest, -> {order(:created_at => :DESC)}
	scope :posts, -> {where(:post_type => :POST)}
	scope :news, -> {where(:post_type => :NEWS)}

	mount_uploader :image, ImageUploader

	def self.get_posts(chinese)
		if chinese
			feature_posts = FeaturePost.select("id, title_cn AS title, content_cn AS content, cover_image, created_at")
			trend_posts = TrendPost.select("id, title_cn AS title, content_cn AS content, cover_image, created_at")
			on_court_posts = OnCourtPost.select("id, title_cn AS title, content_cn AS content, cover_image, created_at").with_link
			street_snap_posts = StreetSnapPost.select("id, title_cn AS title, content_cn AS content, cover_image, created_at")
			rumor_posts = RumorPost.select("id, title_cn AS title, content_cn AS content, cover_image, created_at")
		else
			feature_posts = FeaturePost.select("id, title_en AS title, content_en AS content, cover_image, created_at")
			trend_posts = TrendPost.select("id, title_en AS title, content_en AS content, cover_image, created_at")
			on_court_posts = OnCourtPost.select("id, title_en AS title, content_en AS content, cover_image, created_at").with_link
			street_snap_posts = StreetSnapPost.select("id, title_en AS title, content_en AS content, cover_image, created_at")
			rumor_posts = RumorPost.select("id, title_en AS title, content_en AS content, cover_image, created_at")
		end

		return (feature_posts + trend_posts + on_court_posts + street_snap_posts + rumor_posts).sort_by(&:created_at).reverse.each {|post| post.content = post.content.blank? ? '' : YAML.load(post.content)}
	end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController

	skip_before_filter :verify_authenticity_token, :only => [:destroy, :delete_subscriber]
	before_action :get_post, :only => [:edit, :destroy, :update, :show]

	def index
		@page_title = "Posts | Kicks4Love Admin"
		@posts = Post.posts
		@news = Post.news
		@subscribers = Subscriber.all
	end

	def new
		@post = Post.new
		@page_title = "New Post | Kicks4Love Admin"
	end

	def create
		post = Post.new post_params

		if post.save
			redirect_to admin_posts_path, :notice => "New post successfully created"
		else
			redirect_to :back, :alert => "Error creating new post"
		end
	end

	def update
		if @post.update_attributes(post_params)
			flash[:notice] = "The post has been successfully updated"
		else
			flash[:alert] = "Error occurs while updating the post, please try again"
		end

		redirect_to admin_posts_path
	end

	def edit
		@page_title = "Edit Post | Kicks4Love Admin"
	end

	def destroy
		id = @post.id
		if @post.destroy
			Admin::AdminHelper.remove_uploads_file('post', id)
			flash[:notice] = "The post has been deleted successfully"
		else
			flash[:alert] = "Error occurs while deleting the post, please try again"
		end

		redirect_to admin_posts_path
	end

	# JSON API getting lastest posts
	def get_posts
		head :ok and return unless params[:type].present?

		case params[:type].downcase
		when "features"
			posts = FeaturePost.select(:id, :title_en).latest
		when "calendar"
			posts = CalendarPost.select(:id, :title_en).latest
		when "trend"
			posts = TrendPost.select(:id, :title_en).latest
		when "on_court"
			posts = OnCourtPost.select(:id, :title_en).latest
		when "street_snap"
			posts = StreetSnapPost.select(:id, :title_en).latest
		when "rumors"
			posts = RumorPost.select(:id, :title_en).latest
		end

		render :json => posts.to_json, :layout => false
	end

	def delete_subscriber
		subscriber = Subscriber.find_by_id(params[:id])
		subscriber.delete

		head :ok
	end

	def send_newsletter
		begin
			CustomerServiceMailer.send_newsletter(Subscriber.all).deliver
			flash[:notice] = "Newsletter sent"
		rescue Net::SMTPAuthenticationError, Net::SMTPServerBusy, Net::SMTPSyntaxError, Net::SMTPFatalError, Net::SMTPUnknownError => e
			flash[:alert] = "Somthing wrong happened: " + e.message
		end
		redirect_to :back
	end

	private

	def post_params
		params.require(:post).permit(:title_en, :title_cn, :post_type, :pointer_type, :pointer_id, :image)
	end

	def get_post
		@post = Post.find_by_id(params[:id])
	end

end

app/views/admin/posts/_form.html.erb
<% is_new_record = @post.new_record? %>
<div class="row no-margin">
	<div class="col-sm-2">
		<label>Title (English):</label>
	</div>
	<div class="col-sm-2">
		<%= form.text_field :title_en %>
	</div>
</div>
<br>
<div class="row no-margin">
	<div class="col-sm-2">
		<label>中文标题:</label>
	</div>
	<div class="col-sm-2">
		<%= form.text_field :title_cn %>
	</div>
</div>
<br>
<div class="row no-margin">
	<div class="col-sm-2">
		<label>Pointer Type:</label>
	</div>
	<div class="col-sm-2">
		<%= form.select :pointer_type, Post.pointer_types.keys %>
	</div>
	<div class="col-sm-2">
		<%= form.select :pointer_id, is_new_record ? [] : @post.pointer_type %>
	</div>
</div>
<br>
<div class="row no-margin">
	<div class="col-sm-2">
		<label>Post Type:</label>
	</div>
	<div class="col-sm-2">
		<%= form.text_field :post_type, :value => is_new_record ? params[:type] : @post.post_type, :readonly => true %>
	</div>
</div>
<br>
<div class="row no-margin">
	<div class="col-sm-2">
		<label>Image:</label>
	</div>
	<div class="col-sm-2">
		<%= form.file_field :image %>
	</div>
</div>
<br>
<%= form.submit "Submit", :class => "btn btn-primary" %>

app/views/admin/posts/edit.html.erb
<h1>Edit <%= @post.post_type.titleize %></h1>

<hr/><br/>

<%= form_for @post, :url => admin_post_path(@post), :method => :PUT do |f| %>
	<%= render :partial => "form", :locals => {:form => f} %>
<% end %>

<br/>

<%= link_to "Back", admin_posts_path, :class => "btn btn-default" %> 

<% content_for :end_of_body do %>
    <%= javascript_include_tag "admin/posts.js" %>
<% end %>

app/views/admin/posts/index.html.erb
<h1>Admin Post</h1>

<br/>
<% if @posts.any? && @news.any? %>
	<%= form_tag(send_newsletter_admin_posts_path, method: :post) do%>
		<%= submit_tag 'Send weekly newsletter', :class => "btn btn-info", :onclick => "return confirm('Are you sure?')"%>
	<% end %>
<% end %>
<% if @subscribers.any? %>
	<%= link_to "View all subscribers", '#', :id => "view-all-subscribers" %>
<% end %>
<div id="subscribers-dialog" title="All Subscribers" style="display:none">
	<% @subscribers.each do |subscriber| %>
		<div class="row">
			<%= link_to "Delete", delete_subscriber_admin_post_path(subscriber), :class => "delete-subscriber" %>
			| 
			<%= subscriber.email %>
		</div>
	<% end %>
</div>

<hr/>

<% if @posts.any? %>
	<% if @posts.count == 5 %>
		<h2>Maximum 5 Posts</h2>
	<% else %>
		<%= link_to "Create new post", new_admin_post_path(:type => :POST), :class => "btn btn-primary" %>
	<% end %>

	<br/><br/>

	<table class="table table-bordered">
		<tbody>
			<tr>
				<th></th>
				<th>Type</th>
				<th>Pointer Type</th>
				<th>Title (English)</th>
				<th>中文标题</th>
				<th>Image</th>
			</tr>
		</tbody>
		<tbody>
			<% @posts.each do |post| %>
				<tr>
					<td>
						<%= link_to "Edit", edit_admin_post_path(post) %>
						|
						<%= link_to "Delete", admin_post_path(post), :data => {:confirm => 'Are you sure?'}, :method => :delete %>
					</td>
					<td><%= post.post_type %></td>
					<td><%= post.pointer_type %></td>
					<td><%= post.title_en %></td>
					<td><%= post.title_cn %></td>
					<td><img src="<%= post.image.url %>" height="50px"/></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<h2>No Record</h2>

	<br/>

	<%= link_to "Create a new post now", new_admin_post_path(:type => :POST), :class => "btn btn-primary" %>
<% end %>

<hr/>

<% if @news.any? %>
	<% if @news.count == 3 %>
		<h2>Maximum 3 Posts</h2>
	<% else %>
		<%= link_to "Create new news", new_admin_post_path(:type => :NEWS), :class => "btn btn-primary" %>
	<% end %>

	<br/><br/>

	<table class="table table-bordered">
		<tbody>
			<tr>
				<th></th>
				<th>Type</th>
				<th>Pointer Type</th>
				<th>Title (English)</th>
				<th>中文标题</th>
				<th>Image</th>
			</tr>
		</tbody>
		<tbody>
			<% @news.each do |news| %>
				<tr>
					<td>
						<%= link_to "Edit", edit_admin_post_path(news) %>
						|
						<%= link_to "Delete", admin_post_path(news), :data => {:confirm => 'Are you sure?'}, :method => :delete %>
					</td>
					<td><%= news.post_type %></td>
					<td><%= news.pointer_type %></td>
					<td><%= news.title_en %></td>
					<td><%= news.title_cn %></td>
					<td><img src="<%= news.image.url %>" height="50px"/></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<h2>No Record</h2>

	<br/>

	<%= link_to "Create a new news now", new_admin_post_path(:type => :NEWS), :class => "btn btn-primary" %>
<% end %>

<br/><br/>

<p><%= link_to "Back", admin_root_path, :class => "btn btn-default" %></p>

<% content_for :end_of_body do %>
    <%= javascript_include_tag "admin/posts.js" %>
<% end %>

app/views/admin/posts/new.html.erb
<h1>New <%= params[:type].titleize %></h1>

<hr/><br/>

<%= form_for @post, :url => admin_posts_path do |f| %>
	<%= render :partial => "form", :locals => {:form => f} %>
<% end %>

<br/>

<%= link_to "Back", admin_posts_path, :class => "btn btn-default" %> 

<% content_for :end_of_body do %>
    <%= javascript_include_tag "admin/posts.js" %>
<% end %>