config/routes.rb
Rails.application.routes.draw do

  root :to => 'main#index'

  get '/features' => 'main#features'
  get '/features/:id' => 'main#feature_show'
  get '/calendar' => 'main#calendar'
  get '/trend' =>'main#trend'
  get '/trend/:id' => 'main#trend_show'
  get '/oncourt' => 'main#oncourt'
  get '/oncourt/:id' => 'main#oncourt_show'
  get '/streetsnap' => 'main#streetsnap'
  get '/streetsnap/:id' => 'main#streetsnap_show'
  get '/rumors' => 'main#rumors'
  get '/rumors/:id' => 'main#rumor_show'
  get '/privacy' => 'main#privacy'
  get '/contact_us' => 'main#contact'
  get '/search' => 'main#search'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :main do
  	collection do
  		get 'get_posts'
      post 'change_language'
      post 'send_contact_us'
      post 'post_rating'
      post 'subscribe'
  	end
  end

  get '/admin', :to => 'admin/dashboard#index', :as => :admin_root

  devise_for :admin_users, :controllers => {:sessions => 'admin/sessions', :registrations => "admin/registrations"}, :skip => [:sessions, :registrations]
  devise_scope :admin_user do
    get 'admin/login' => 'admin/sessions#new', :as => :new_admin_user_session
    post 'admin/login' => 'admin/sessions#create', :as => :admin_user_session
    delete 'admin/logout' => 'admin/sessions#destroy', :as => :destroy_admin_user_session
    get 'admin/register' => 'admin/registrations#new', :as => :new_admin_user_registration
    post 'admin/register' => 'admin/registrations#create', :as => :admin_user_registration
    get 'admin/register/:id/edit' => 'admin/registrations#edit', :as => :edit_admin_user_registration
    put 'admin/register' => 'admin/registrations#update'
  end

  namespace :admin do
  	resources :posts do
      collection do
        get 'get_posts'
        post 'send_newsletter'
      end
      member do
        delete 'delete_subscriber'
      end
    end
    resources :feature_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :calendar_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :trend_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :on_court_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :rumor_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :street_snap_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :admin_users
  end

  get '/sitemap.xml', :to => 'sitemap#index', :defaults => {:format => 'xml'}

  namespace :api do
    scope :v0 do
      scope :home_posts do
        get '/' => 'home_posts#index'
      end
      scope :featured_posts do
        get '/' => 'featured_posts#index'
        get '/:id' => 'featured_posts#show'
      end
      scope :oncourt_posts do
        get '/' => 'oncourt_posts#index'
        get '/:id' => 'oncourt_posts#show'
      end
      scope :trend_posts do
        get '/' => 'trend_posts#index'
        get '/:id' => 'trend_posts#show'
      end
      scope :streetsnap_posts do
        get '/' => 'streetsnap_posts#index'
        get '/:id' => 'streetsnap_posts#show'
      end
      scope :rumor_posts do
        get '/' => 'rumor_posts#index'
        get '/:id' => 'rumor_posts#show'
      end
      scope :calendar_posts do
        get '/' => 'calendar_posts#index'
      end
      get '/search' => 'api_base#search'
      post '/rate' => 'api_base#rate'
      post '/email' => 'api_base#email'
    end
  end

end

app/models/trend_post.rb
require 'elasticsearch/model'

class TrendPost < ApplicationRecord

  include Elasticsearch::Model
  #include Elasticsearch::Model::Callbacks

	attr_accessor :post_type

	serialize :content_en, Array
	serialize :content_cn, Array
	serialize :main_images, JSON

  has_many :rates, :as => :post, :dependent => :destroy
  belongs_to :author, class_name: "AdminUser"

  scope :latest, -> {order(:created_at => :DESC)}
	scope :old, -> {where("created_at < ?", 3.month.ago)}

  self.per_page = 3
  MAX_NUMBER_ALLOW = 6

  mount_uploader :cover_image, ImageUploader
  mount_uploaders :main_images, ImageUploader

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :title_en
      indexes :title_cn
      indexes :content_cn
      indexes :content_en
    end
  end

  def self.as_indexed_json(options={})
    self.as_json({only: [:title_en, :title_cn, :content_en, :content_cn]})
  end

end

TrendPost.import force: true

app/controllers/admin/trend_posts_controller.rb
class Admin::TrendPostsController < Admin::AdminController
	
	skip_before_filter :verify_authenticity_token, :only => [:destroy]
	before_action :get_trend_post, :only => [:edit, :destroy, :update, :show]

	def index
		@page_title = "Trend Posts | Kicks4Love Admin"
		@trend_posts = TrendPost.latest
		@expired_posts_count = TrendPost.old.size;
		if params[:filter].present?
			session[:trend_post_per_page] = params[:filter][:per_page].to_i
		end
		@per_page = session[:trend_post_per_page] || 10
		@trend_posts = @trend_posts.paginate(:page => params[:page] || 1, :per_page => session[:trend_post_per_page] || 10)
	end

	def new
		@trend_post = TrendPost.new
		@page_title = "New Trend Post | Kicks4Love Admin"
	end

	def create
		trend_post = TrendPost.new process_content(trend_post_params)
		trend_post.author = current_admin_user

		if trend_post.content_en.count > TrendPost::MAX_NUMBER_ALLOW || trend_post.content_cn.count > TrendPost::MAX_NUMBER_ALLOW
	      redirect_to :back, :alert => "Maximum paragraph number is #{TrendPost::MAX_NUMBER_ALLOW}"
	      return
	    elsif trend_post.main_images.count > TrendPost::MAX_NUMBER_ALLOW
	      redirect_to :back, :alert => "Maximum main image number is #{TrendPost::MAX_NUMBER_ALLOW}"
	      return
	    end

		if trend_post.save
			redirect_to admin_trend_posts_path, :notice => "New trend post successfully created"
		else
			redirect_to :back, :alert => "Error creating new trend post"
		end
	end

	def update
		params = process_content(trend_post_params)

		if params[:content_en].count > TrendPost::MAX_NUMBER_ALLOW || params[:content_cn].count > TrendPost::MAX_NUMBER_ALLOW
      		redirect_to :back, :alert => "Maximum paragraph number is #{TrendPost::MAX_NUMBER_ALLOW}"
      		return
    	elsif params[:main_images].present? && params[:main_images].count > TrendPost::MAX_NUMBER_ALLOW
      		redirect_to :back, :alert => "Maximum main image number is #{TrendPost::MAX_NUMBER_ALLOW}"
      		return
    	end
		@trend_post.author = current_admin_user if @trend_post.author.nil?
		if @trend_post.update_attributes(params)
			flash[:notice] = "The trend post has been successfully updated"
		else
			flash[:alert] = "Error occurs while updating the trend post, please try again"
		end

		redirect_to admin_trend_posts_path
	end

	def edit
		@page_title = "Edit Trend Post | Kicks4Love Admin"
		@trend_post.content_en = @trend_post.content_en.map {|p| '>>' + p}
		@trend_post.content_cn = @trend_post.content_cn.map {|p| '>>' + p}
	end

	def destroy
		id = @trend_post.id
		if @trend_post.destroy
			Admin::AdminHelper.remove_uploads_file('trend_post', id)
			flash[:notice] = "The trend post has been deleted successfully"
		else
			flash[:error] = "Error occurs while deleting the trend post, please try again"
		end

		redirect_to admin_trend_posts_path
	end

	def remove_old
		old_posts = TrendPost.old
		return_posts = old_posts.to_a
		if old_posts.destroy_all
			return_posts.each {|post| Admin::AdminHelper.remove_uploads_file('trend_post', post.id)}
			render :json => return_posts.to_json, :layout => false
		else
			head :ok, :status => 500
		end
	end

	private

	def trend_post_params
		params.require(:trend_post)
		.permit(:title_en, :title_cn, :content_en, :content_cn, :cover_image, {main_images: []}, :remove_main_images)
	end

	def process_content(params)
		params[:content_en] = params[:content_en].split(/\r?\n/).map {|p| Admin::AdminHelper.trim_str(p)}
		params[:content_cn] = params[:content_cn].split(/\r?\n/).map {|p| Admin::AdminHelper.trim_str(p)}
    	return params
  	end

	def get_trend_post
		@trend_post = TrendPost.find_by_id(params[:id])
	end

end

app/controllers/api/trend_posts_controller.rb
class Api::TrendPostsController < Api::ApiBaseController

  def index
    @return_posts = []

    if params[:next_page].present?
      feeds = TrendPost.paginate(:page => params[:next_page], :per_page => 6).latest
      @no_more = feeds.total_pages <= feeds.current_page
      unless feeds.blank?
        if @chinese
          feeds = feeds.select("id, title_cn AS title, cover_image, created_at, author_id")
        else
          feeds = feeds.select("id, title_en AS title, cover_image, created_at, author_id")
        end
        @return_posts = Api::ApiHelper.reformat_feeds(feeds, root_url.chop)
      end
    else
      @no_more = true
    end

    render json: Api::ApiHelper.json_response(@no_more, @return_posts), status: :ok
  end

  def show
    begin
      post = TrendPost.find(params[:id])
      return_post = Api::ApiHelper.format_post(post, root_url.chop)
      render json: return_post.to_json, status: :ok
    rescue ActiveRecord::RecordNotFound => e
      render json: { message: e.message }.to_json, status: :not_found
    end
  end

end

app/views/admin/trend_posts/_form.erb
<div class="row no-margin">
	<div class="col-sm-2">
		<label>Title (English):</label>
	</div>
	<div class="col-sm-2">
		<%= form.text_field :title_en %>
	</div>
</div>
<br>
<div class="row no-margin">
	<div class="col-sm-2">
		<label>中文标题:</label>
	</div>
	<div class="col-sm-2">
		<%= form.text_field :title_cn %>
	</div>
</div>
<br>
<div class="row no-margin">
	<div class="col-sm-2">
		<label>Content (English):</label>
	</div>
	<div class="col-sm-2">
		<%= form.text_area :content_en, :class => 'content-form', :value => @trend_post.content_en.join("\n"), :title => "Different paragraph in different line" %>
	</div>
</div>
<br>
<div class="row no-margin">
	<div class="col-sm-2">
		<label>文章内容（中文):</label>
	</div>
	<div class="col-sm-2">
		<%= form.text_area :content_cn, :class => 'content-form', :value => @trend_post.content_cn.join("\n"), :title => "Different paragraph in different line" %>
	</div>
</div>
<br>
<div class="row no-margin">
	<div class="col-sm-2">
		<label>Cover Image:</label>
	</div>
	<div class="col-sm-2">
		<%= form.file_field :cover_image %>
	</div>
</div>
<br>
<div class="row no-margin">
	<div class="col-sm-2">
		<label>Main Images:</label>
	</div>
	<div class="col-sm-2">
		<%= form.file_field :main_images, :multiple => true %>
	</div>
</div>
<div class="row no-margin">
	<% if @trend_post.main_images.count > 0 %>
		<label>
    		<%= form.check_box :remove_main_images %> Remove current images
		</label>
	<% end %>
</div>
<br>
<%= form.submit "Submit", :class => "btn btn-primary" %>

app/views/admin/trend_posts/edit.html.erb
<h1>Edit Trend Post</h1>

<hr/><br/>

<%= form_for @trend_post, :url => admin_trend_post_path(@trend_post), :method => :PUT do |f| %>
	<%= render :partial => "form", :locals => {:form => f} %>
<% end %>

<br/>

<%= link_to "Back", admin_trend_posts_path, :class => "btn btn-default" %>

<% content_for :end_of_body do %>
    <%= javascript_include_tag "admin/trend.js" %>
<% end %>

app/views/admin/trend_posts/index.html.erb
<h1>Admin Trend Post</h1>

<hr/>

<% if @trend_posts.any? %>
  <%= link_to "New Trend Post", new_admin_trend_post_path, :class => "btn btn-primary" %>
  <% if @expired_posts_count > 0 %>
    <button id="remove-old" class="btn btn-danger">Delete <%= @expired_posts_count %> old posts</button>
  <% end %>

  <br/><br/>

  <%= form_for :filter, :url => admin_trend_posts_path, :method => :get, :html => {:class => "filter-form"} do |f| %>
      <label>Per Page:</label>
      <%= f.radio_button :per_page, 5, :checked => @per_page == 5 %>
      <%= f.label :per_page, 5, :value => 5 %>
      <%= f.radio_button :per_page, 10, :checked => @per_page == 10 %>
      <%= f.label :per_page, 10, :value => 10  %>

      <%= f.submit 'Filter', :class => "btn btn-default"  %>
      <%= link_to 'Clear Filter', admin_trend_posts_path %>
  <% end %>
  <br/>
  <div id="more-dialog" title="More Information"></div>
  <table class="table table-bordered">
    <thead>
        <tr>
          <th></th>
          <th>Author</th>
          <th>Title (English)</th>
          <th>中文标题</th>
          <th>Content (English)</th>
          <th>文章内容 （中文)</th>
          <th>Cover Image</th>
          <th>Main Image</th>
        </tr>
    </thead>
    <tbody>
      <% @trend_posts.each do |trend_post| %>
        <tr data-id="<%= trend_post.id %>">
          <td>
            <%= link_to "Edit", edit_admin_trend_post_path(trend_post) %>
            |
            <%= link_to "Delete", admin_trend_post_path(trend_post), :data => {:confirm => 'Are you sure?'}, :method => :delete %>
            |
            <%
              rates = trend_post.rates
              rates_json = {
                :one => rates.where(:score => 1).count,
                :two => rates.where(:score => 2).count,
                :three => rates.where(:score => 3).count,
                :four => rates.where(:score => 4).count,
                :five => rates.where(:score => 5).count
              }.to_json
            %>
            <a href="#" class="more-dialog-btn" data-rates="<%= rates_json %>">More</a>
          </td>
          <td>
            <% if trend_post.author.nil? %>
              No author
            <% else %>
              <%= trend_post.author.username.empty? ? trend_post.author.email : trend_post.author.username %>
            <% end %>
          </td>
          <td><%= trend_post.title_en %></td>
          <td><%= trend_post.title_cn %></td>
          <% if trend_post.content_en.any?%>
            <td>
            <%= trend_post.content_en.size %> paragraphs
            </td>
          <% else %>
            <td>No content in English</td>
          <% end %>
          <% if trend_post.content_cn.any?%>
            <td>
            <%= trend_post.content_cn.size %> 段
            </td>
          <% else %>
            <td>暂无中文内容</td>
          <% end %>
          <td><img src="<%= trend_post.cover_image %>" height = "50px" /></td>
          <td><%= trend_post.main_images.size %> main images</td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @trend_posts, :previous_label => 'Prev', :next_label => 'Next' %>
<% else %>
    <h2>No Record</h2>

    <br/>

    <%= link_to "Create a new on trend post now", new_admin_trend_post_path, :class => "btn btn-primary" %>
<% end %>

<br/><br/>

<p><%= link_to "Back", admin_root_path, :class => "btn btn-default" %></p>
<% content_for :end_of_body do %>
    <%= javascript_include_tag "admin/trend.js" %>
<% end %>

app/views/admin/trend_posts/new.html.erb
<h1>New Trend Posts</h1>

<hr/><br/>

<%= form_for @trend_post, :url => admin_trend_posts_path do |f| %>
  <%= render :partial => "form", :locals => {:form => f} %>
<% end %>

<%link_to "Back", admin_trend_posts_path, :class => "btn btn-default" %>

<% content_for :end_of_body do %>
    <%= javascript_include_tag "admin/trend.js" %>
<% end %>