config/routes.rb
Rails.application.routes.draw do

  root :to => 'main#index'

  get '/features' => 'main#features'
  get '/features/:id' => 'main#feature_show'
  get '/calendar' => 'main#calendar'
  get '/trend' =>'main#trend'
  get '/trend/:id' => 'main#trend_show'
  get '/oncourt' => 'main#oncourt'
  get '/oncourt/:id' => 'main#oncourt_show'
  get '/streetsnap' => 'main#streetsnap'
  get '/streetsnap/:id' => 'main#streetsnap_show'
  get '/rumors' => 'main#rumors'
  get '/rumors/:id' => 'main#rumor_show'
  get '/privacy' => 'main#privacy'
  get '/contact_us' => 'main#contact'
  get '/search' => 'main#search'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :main do
  	collection do
  		get 'get_posts'
      post 'change_language'
      post 'send_contact_us'
      post 'post_rating'
      post 'subscribe'
  	end
  end

  get '/admin', :to => 'admin/dashboard#index', :as => :admin_root

  devise_for :admin_users, :controllers => {:sessions => 'admin/sessions', :registrations => "admin/registrations"}, :skip => [:sessions, :registrations]
  devise_scope :admin_user do
    get 'admin/login' => 'admin/sessions#new', :as => :new_admin_user_session
    post 'admin/login' => 'admin/sessions#create', :as => :admin_user_session
    delete 'admin/logout' => 'admin/sessions#destroy', :as => :destroy_admin_user_session
    get 'admin/register' => 'admin/registrations#new', :as => :new_admin_user_registration
    post 'admin/register' => 'admin/registrations#create', :as => :admin_user_registration
    get 'admin/register/:id/edit' => 'admin/registrations#edit', :as => :edit_admin_user_registration
    put 'admin/register' => 'admin/registrations#update'
  end

  namespace :admin do
  	resources :posts do
      collection do
        get 'get_posts'
        post 'send_newsletter'
      end
      member do
        delete 'delete_subscriber'
      end
    end
    resources :feature_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :calendar_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :trend_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :on_court_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :rumor_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :street_snap_posts do
      collection do
        get 'remove_old'
      end
    end
    resources :admin_users
  end

  get '/sitemap.xml', :to => 'sitemap#index', :defaults => {:format => 'xml'}

  namespace :api do
    scope :v0 do
      scope :home_posts do
        get '/' => 'home_posts#index'
      end
      scope :featured_posts do
        get '/' => 'featured_posts#index'
        get '/:id' => 'featured_posts#show'
      end
      scope :oncourt_posts do
        get '/' => 'oncourt_posts#index'
        get '/:id' => 'oncourt_posts#show'
      end
      scope :trend_posts do
        get '/' => 'trend_posts#index'
        get '/:id' => 'trend_posts#show'
      end
      scope :streetsnap_posts do
        get '/' => 'streetsnap_posts#index'
        get '/:id' => 'streetsnap_posts#show'
      end
      scope :rumor_posts do
        get '/' => 'rumor_posts#index'
        get '/:id' => 'rumor_posts#show'
      end
      scope :calendar_posts do
        get '/' => 'calendar_posts#index'
      end
      get '/search' => 'api_base#search'
      post '/rate' => 'api_base#rate'
      post '/email' => 'api_base#email'
    end
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  	<head>
  	    <title><%= @page_title || "Kicks4Love Admin" %></title>
  	    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
  	    <meta name="viewport" content="width=device-width, initial-scale=1">
  	    <meta name="description" content="Kicks4Love Admin">
  	    <meta name="author" content="RHBoys">

        <!-- Custom CSS -->
        <%= stylesheet_link_tag "admin/admin.css" %>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.min.css">

        <!-- Third Party JS -->
        <%= javascript_include_tag "admin/admin.js" %>
        <script async src="https://code.jquery.com/ui/1.10.4/jquery-ui.min.js"></script>
	  </head>
  	<body>
        <%= content_for :head %>

        <% if admin_user_signed_in? %>
            <div class="nav current-admin-user-bar">
           		  <div class="col-xs-8">
                    <strong><%= link_to 'Admin Home', admin_root_path %></strong> |
           			    <label>Login As</label>
                    <%= link_to current_admin_user.email, admin_admin_user_path(current_admin_user) %>
           		  </div>
           		  <div class="col-xs-4 text-right">
           			    <%= link_to "Logout", destroy_admin_user_session_path, :method => :delete %>
           		  </div>
           	</div>
        <% end %>

        <% if notice %>
              <div class="alert alert-success"><%= notice %></div>
        <% end %>
        <% if alert %>
              <div class="alert alert-danger"><%= alert %></div>
        <% end %>

        <div class="container">
    	      <%= yield %>
        </div>

        <%= content_for :end_of_body %>
  	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<%= cookies[:language] || 'en' %>" xml:lang="<%= cookies[:language] || 'en' %>">
    <head>
        <title><%= @page_title || "Kicks4Love鞋侣" %></title>
        <%= favicon_link_tag 'favicon.png' %>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="The destination for all sneaker fans and trend enthusiasts 所有球鞋热爱家和潮流脑残粉的终极平台">
        <meta name="author" content="RHBoys">
        <meta property="og:image" content="<%= @og_image || image_url('main_logo.png') %>" />

        <!-- Common CSS -->
        <%= stylesheet_link_tag "application.css" %>

        <!-- Custom Fonts -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- Common JS -->
        <script>
        	var facebookAppId = "<%= Rails.application.config.social_media[:facebook_app_id] %>";
        	var weiboUId = "<%= Rails.application.config.social_media[:weibo_u_id] %>";
        </script>
        <%= javascript_include_tag "application.js" %>
        <!--<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>-->
        <script async src='https://www.google-analytics.com/analytics.js'></script>
	</head>
    <body>
      	<%= content_for :head %>
      	<%= hidden_field_tag "language-set", cookies[:language] %>

        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            		    <span class="sr-only">Toggle navigation</span>
            		    <span class="icon-bar"></span>
            		    <span class="icon-bar"></span>
            		    <span class="icon-bar"></span>
                    </button>
                    <%= link_to image_tag("nav_logo.png", :width => "175", :alt => "Kicks4Love鞋侣"), :root, :class => "navbar-brand" %>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><%= link_to t("HOME"), root_path %></li>
                        <li><%= link_to t("FEATURES"), features_path %></li>
                        <li><%= link_to t("CALENDAR"), calendar_path %></li>
                        <li class="dropdown">
        			        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t("MORE") %><span class="caret"></span></a>
        			        <ul class="dropdown-menu">
                		        <li><%= link_to t("TREND"), trend_path %></li>
                		        <li><%= link_to t("ON_COURT"), oncourt_path %></li>
                		        <li role="separator" class="divider"></li>
                		        <li class="dropdown-header"><%= t("LEISURE_ENTERTAINMENT") %></li>
                		        <li><%= link_to t("STREET_SNAP"), streetsnap_path %></li>
                                <li><%= link_to t("RUMORS"), rumors_path %></li>
             			    </ul>
      			       </li>
    		        </ul>
      				<div class ="navbar-form navbar-right" role="search">
                        <%= form_tag(search_path, :method => :get, :class => "search-form") do %>
                            <div class="input-group">
              			       <%= text_field_tag :q, params[:q], :placeholder => t("What_are_you_looking_for"), :type => "text", :class => "form-control" %>
                                <span class="input-group-btn"><%= button_tag t("Go"), :name => nil, :class => "btn btn-secondary" %></span>
                            </div>
              	        <% end %>
      				</div>
                    <ul id="side-nav-mobile" class="visible-xs-block clearfix">
                        <li class="col-xs-3">
                            <a href='#' class="show-subscribe">
                                <i class="fa fa-rss"></i>
                                <span><%= t("Feed") %></span>
                            </a>
                        </li>
                        <li class="col-xs-3">
                            <a href='#' class="not-work">
                                <i class="fa fa-shopping-cart"></i>
                                <span><%= t("Shop") %></span>
                            </a>
                        </li>
                        <li class="col-xs-3">
                            <a href='#' data-toggle="modal" data-target="#language-modal">
                                <i class="fa fa-language"></i>
                                <span><%= t("Lang") %></span>
                            </a>
                        </li>
                        <li class="col-xs-3">
                            <a href="<%= contact_us_path %>">
                                <i class="fa fa-envelope"></i>
                                <span><%= t("Mail") %></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="logo-pendant" style="opacity:0"><%= image_tag "main_logo.png", :alt => "Kicks4Love鞋侣" %></div>
        <div id='side-nav' class="hidden-xs">
		    <ul>
  			    <li>
    			    <a href='#' class="show-subscribe">
      			       <i class="fa fa-rss"></i>
      			       <span><%= t("Subscribe") %></span>
    			    </a>
                </li>
                <li>
  			        <a href='#' class="not-work">
    				    <i class="fa fa-shopping-cart"></i>
    				    <span><%= t("Store") %></span>
  			        </a>
			    </li>
			    <li>
  			        <a href='#' data-toggle="modal" data-target="#language-modal">
    				    <i class="fa fa-language"></i>
    				    <span><%= t("Language") %></span>
  			        </a>
			    </li>
			    <li>
  			        <a href="<%= contact_us_path %>">
    				    <i class="fa fa-envelope"></i>
    				    <span><%= t("Contact_Us") %></span>
  			        </a>
			    </li>
            </ul>
        </div>
        <% if notice %>
    	    <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				    <span aria-hidden="true">&times;</span>
			    </button>
                <%= notice %>
            </div>
        <% end %>
        <% if alert %>
            <div class="alert alert-danger alert-dismissible" role="alert">
      	        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		            <span aria-hidden="true">&times;</span>
	            </button>
      	        <%= alert %>
            </div>
        <% end %>
        <noscript>
            <div class="alert alert-danger alert-dismissible" role="alert">
	            <p><%= t("noscript_message") %></p>
            </div>
        </noscript>
        <div id="language-modal" class="modal fade" role="dialog">
		    <div class="modal-dialog">
			    <div class="modal-content">
                    <div class="modal-header">
	                    <button type="button" class="close" data-dismiss="modal">&times;</button>
	                    <h4 class="modal-title">请选择您的语言</h4>
	                    <h4 class="modal-title">Please choose your language</h4>
                    </div>
                    <div class="modal-body">
                        <%= form_tag url_for(:controller => "main", :action => "change_language"), :id => "language-form", :method => "post" do %>
	                        <%= submit_tag '中文', :onclick => "this.form.submited=this.name;", :class => "btn chinese-option", :name => "language[chinese]" %>
                            <%= submit_tag 'English', :onclick => "this.form.submited=this.name;", :class => "btn english-option", :name => "language[english]" %>
                        <% end %>
                    </div>
                    <div class="modal-footer">
	                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
			    </div>
		    </div>
        </div>
 
        <%# unless controller.action_name == "index" %>
            <!-- Google Adsense
            <ins class="adsbygoogle top-ad" style="display:block" data-ad-client="ca-pub-4802332774820705" data-ad-slot="7048272677" data-ad-format="auto"></ins>
            <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
            -->
        <%# end %>

	    <%= yield %>

        <!-- Google Adsense
        <ins class="adsbygoogle bottom-ad" style="display:block" data-ad-client="ca-pub-4802332774820705" data-ad-slot="7048272677" data-ad-format="auto"></ins>
        <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
        -->

	    <div class="social-media">
		    <a href="<%= Rails.application.config.social_media[:facebook] %>" target="_blank" class="fa-stack fa-lg">
        		<i class="fa fa-circle-thin fa-stack-2x"></i>
        		<i class="fa fa-facebook fa-stack-1x"></i>
      		</a>
      		<a href="<%= Rails.application.config.social_media[:weibo] %>" target="_blank" class="fa-stack fa-lg">
        		<i class="fa fa-circle-thin fa-stack-2x"></i>
        		<i class="fa fa-weibo fa-stack-1x"></i>
      		</a>
      		<a href="<%= Rails.application.config.social_media[:instagram] %>" target="_blank" class="fa-stack fa-lg">
        		<i class="fa fa-circle-thin fa-stack-2x"></i>
        		<i class="fa fa-instagram fa-stack-1x"></i>
      		</a>
            <div id="scroll-top">
                <i class="fa fa-chevron-up fa-2x" aria-hidden="true"></i>
            </div>
	    </div>
        <div class="subscribe">
            <i class="fa fa-times" aria-hidden="true"></i>
            <%= form_tag(subscribe_main_index_path, :method => "post", :class => "form-inline verticle-center", :id => "signup-form") do %>
                <div class="input-group">
                    <%= email_field_tag :email, nil, class: "form-control", placeholder: t("email_here") %>
                    <span class="input-group-btn"><%= submit_tag t("Sign_up"), data: {disable_with: t("Signing_up")}, class: "btn" %></span>
                </div>
            <% end %>
        </div>
      	<footer>
  		    <div class="container">
  		        <div class="row">
  		            <div class="col-lg-12">
    		            <ul class="list-inline">
                            <li><%= link_to t("Home"), root_path %></li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li><%= link_to t("Features"), features_path %></li>
                            <li class="footer-menu-divider">&sdot;</li>
            				<li><%= link_to t("Calendar"), calendar_path %></li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li><%= link_to t("Trend"), trend_path %></li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li><%= link_to t("On_Court"), oncourt_path %></li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li><%= link_to t("Street_Snap"), streetsnap_path%></li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li><%= link_to t("Rumors"), rumors_path%></li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li><%= link_to t("Privacy"), privacy_path %></li>
                            <li class="footer-menu-divider">&sdot;</li>
                            <li><%= link_to t("Contact_Us"), contact_us_path %></li>
    		            </ul>
  		                <p class="copyright text-muted small">Copyright &copy; Kicks4Love <%= Date.today.year %>. All Rights Reserved</p>
  		            </div>
  		        </div>
  		    </div>
  		</footer>
        <%= content_for :end_of_body %>
  	</body>
</html>